feat: add more error message in action [no ci]

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -83,7 +83,24 @@ runs:
           $MOUNT \
           -t \
           -v /tmp/shopee_bot:/screenshot \
-          ${{ inputs.image }} -c /repo/plain_credential $FLAGS -s /screenshot
+          ${{ inputs.image }} \
+          -c /repo/plain_credential \
+          $FLAGS \
+          -s /screenshot || {
+            exit_code=$?
+          }
+        
+        if [[ $exit_code -eq 3 || $exit_code -eq 69 ]]; then
+          echo '::error::因為嘗試次數過督被蝦皮 ban 了，請明天再試。'
+        elif [[ $exit_code -eq 4 ]]; then
+          echo '::error::操作逾時。如果你沒有收到簡訊，可能是蝦皮的問題。如果你有收到簡訊，請回報開發者。'
+        elif [[ $exit_code -eq 87 ]]; then
+          echo '::error::帳號或密碼錯誤。'
+        elif [[ $exit_code -ne 0 ]]; then
+          echo "::error::發生不明錯誤，錯誤代碼為 $exit_code 。請回報開發者。"
+        fi
+
+        exit $exit_code
 
     - name: Upload error screenshot
       if: ${{ failure() }}
@@ -93,7 +110,6 @@ runs:
         path: /tmp/shopee_bot/screenshot.png
 
     - name: Encrypt credential
-      if: ${{ success() }}
       shell: bash -e {0}
       run: |
         # If the checkout did not succeeded then the credentials is placed 
@@ -119,3 +135,12 @@ runs:
         user_email: bot@hyperbola.me
         commit_message: update credential
         enable_jekyll: true # dont generate .nojekyll file
+
+    - name: Echo hint message
+      shell: bash -e {0}
+      run: |
+        if [[ '${{ github.event_name }}' == 'workflow_dispatch' ]]; then
+          echo "::notice::簽到成功囉，從接下來開始每天凌晨 00:10 會進行排程自動簽到；不過 GitHub Action 的排程常常有數小時的延誤，所以如果發現機器人沒有準時運作的話，就再等一下吧。另外，如果你看到上面有個 \"The process '/usr/bin/git' failed with exit code 1\" 的錯誤訊息，那是正常的，不用理會。"
+        elif [[ '${{ github.event_name }}' == 'schedule' ]]; then
+          echo '::notice::自動簽到成功！'
+        fi
